# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "GB");
user_pref("browser.search.region", "GB");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150525141253");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 743);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150525141253");
user_pref("browser.startup.homepage_override.mstone", "38.0.5");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1450301886627");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1450301886627");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1450301878143");
user_pref("datareporting.policy.firstRunTime", "1450301775332");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 607);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 758);
user_pref("datareporting.sessions.current.startTime", "1457380985006");
user_pref("datareporting.sessions.current.totalTime", 6);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.0", "{\"s\":1450301775097,\"a\":2,\"t\":6,\"c\":true,\"m\":90,\"fp\":864,\"sr\":1016}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1450301867288,\"a\":8,\"t\":36,\"c\":true,\"m\":41,\"fp\":717,\"sr\":851}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1457094355336,\"a\":13,\"t\":79,\"c\":true,\"m\":45,\"fp\":591,\"sr\":804}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1457094440344,\"a\":2,\"t\":10,\"c\":true,\"m\":40,\"fp\":613,\"sr\":810}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1457101193651,\"a\":8,\"t\":79,\"c\":true,\"m\":40,\"fp\":595,\"sr\":790}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1457372090489,\"a\":13,\"t\":61,\"c\":true,\"m\":41,\"fp\":628,\"sr\":838}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1457372161580,\"a\":8,\"t\":37,\"c\":true,\"m\":41,\"fp\":624,\"sr\":758}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1457380890292,\"a\":8,\"t\":55,\"c\":true,\"m\":39,\"fp\":721,\"sr\":877}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0.5");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.0.5");
user_pref("extensions.lastPlatformVersion", "38.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0.5\",\"st\":1432597837000,\"mt\":1432591758000}}}");
user_pref("gecko.buildID", "20150525141253");
user_pref("gecko.mstone", "38.0.5");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1457094417);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150525141253");
user_pref("media.gmp-manager.lastCheck", 1457094417);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1457380985);
user_pref("toolkit.telemetry.previousBuildID", "20150525141253");
