# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "GB");
user_pref("browser.search.region", "GB");
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 881);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "20150525141253");
user_pref("browser.startup.homepage_override.mstone", "38.0.5");
user_pref("browser.startup.page", 0);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("datareporting.healthreport.currentDaySubmissionFailureCount", 1);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1457475827015");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1457476727024");
user_pref("datareporting.healthreport.pendingDeleteRemoteData", true);
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.firstRunTime", "1457475037679");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 872);
user_pref("datareporting.sessions.current.main", 28);
user_pref("datareporting.sessions.current.sessionRestored", 978);
user_pref("datareporting.sessions.current.startTime", "1457986314600");
user_pref("datareporting.sessions.current.totalTime", 9);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.0", "{\"s\":1457474948625,\"a\":0,\"t\":98,\"c\":true,\"m\":88810,\"fp\":89527,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1457475050459,\"a\":6,\"t\":32,\"c\":true,\"m\":5641,\"fp\":6244,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1457475091328,\"a\":1,\"t\":6,\"c\":true,\"m\":2221,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1457475100671,\"a\":1,\"t\":3,\"c\":true,\"m\":41,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1457475515383,\"a\":13,\"t\":68,\"c\":true,\"m\":877,\"fp\":3419,\"sr\":-1}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1457475587672,\"a\":1,\"t\":4,\"c\":true,\"m\":291,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1457475799552,\"a\":9,\"t\":41,\"c\":true,\"m\":241,\"fp\":861,\"sr\":-1}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1457475841587,\"a\":9,\"t\":43,\"c\":true,\"m\":1,\"fp\":449,\"sr\":-1}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0.5");
user_pref("extensions.lastAppVersion", "38.0.5");
user_pref("extensions.lastPlatformVersion", "38.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.6.1\",\"st\":1432597837000,\"mt\":1432591758000}}}");
user_pref("gecko.buildID", "20150525141253");
user_pref("gecko.mstone", "38.0.5");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1457475581);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160216162121");
user_pref("media.gmp-manager.lastCheck", 1457475580);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1457986314);
user_pref("toolkit.telemetry.previousBuildID", "20150525141253");
